move-fast-and-break-things/aibyss

components/CodeEditor.vue
server/botApis/level01.js
server/plugins/engine.ts

https://github.com/move-fast-and-break-things/aibyss/assets/4187729/1b563aba-255a-4161-8ae0-cd6b4e9408db
https://github.com/move-fast-and-break-things/aibyss/assets/4187729/4d413f00-c88a-418d-b547-629ec6fb91e9
N/A

feat: expose `api.worldHeight` and `api.worldWidth` and make the example bot code more interesting

---

eslint.config.mjs

The app will be less likely to crash because we won't be using non-null assertions.
Ditto.
N/A

chore(eslint): disallow non-null assertions

---

.github/workflows/validate.yaml

No impact.
Developers will be able to run CI and merge PRs faster thanks to the `node_modules` cache.
N/A

ci: switch to `ubuntu-24.04` and enable `node_modules` cache

---

components/CodeEditor.vue

fix(code editor): style new buttons as part of the editor

---

server/plugins/engine.ts

https://www.loom.com/share/ec44b3356cb241e5b10f2b91ce6f8307
Ditto.
Было бы здорово защитить эту логику тестом.

fix(engine): restart the game when the bot is 1/2 of the game field height, rather than wait for it to become the game height

---

utils/world.ts

Было бы здорово защитить сбор статистики тестами.

quickfix(world): game stats should count bot deaths

---

README.md

@PlutoniumSoup и @Bee133 сегодня видели, что устанавливать доп зависимости для Windows не нужно. `npm install` всё, что нужно, ставит.
N/A

docs(README): remove not needed Windows setup step from the README

---

server/plugins/engine.ts

We will capture the user bot stats in the db even if they are aren't in the game by the game end.
Ditto.
N/A

fix(engine): don't exclude bots not present in the world at the end of the game from the final stats calculations

---

other/world.spec.ts
other/world.ts

https://github.com/user-attachments/assets/5a827f42-c7d9-47e2-a036-922c9922e831
https://github.com/user-attachments/assets/3e475018-c1f0-4c57-a23e-ce565775d9c6
N/A

fix(world): bots shouldn't be able to leave the game screen

---

server/plugins/engine.ts

This PR fixes the issue where the game may end by time earlier than in the configured 15 minutes.
N/A

fix: game timeout timer should reset on every game start

---

components/CodeEditor.vue
components/GlobalHeader.vue

The issue was accidentally introduced in this commit: https://github.com/move-fast-and-break-things/aibyss/commit/c3c3e3fb04de589cbca07343c848c875a89bd7e9.
N/A

fix: "API reference" and "?" modal sizes

---

components/RatingTable.vue
server/api/rating.get.ts

feat(rating): add "24h score" and "1h score" columns

---

components/RatingChart.vue
components/RatingTable.vue
other/setRgbColorOpacity.test.ts
other/setRgbColorOpacity.ts
package-lock.json
package.json
server/api/rating.get.ts

Merge only after:
This PR lets users view the hourly score graph.
Loom:
https://www.loom.com/share/0c83f60483e4496db407fb033507708b
Depending on how useful this one is, we may want to add other kinds of graphs in the future.

feat(rating): add hourly score graph

---

components/GameScreen.vue

Larger bots will always be rendered above the smaller ones to ensure that "eating" other bots looks natural.
Ditto ⬆️ 
N/A

fix: ensure that larger bots are always rendered above the smaller ones so that "eating" other bots looks more natural

---

other/getRandomElement.spec.ts
other/getRandomElement.ts
other/world.spec.ts
other/world.ts
server/plugins/engine.ts

This PR:
Ditto ⬆️ 
We may need to do some more tuning based on how this works for us 🤷  Excited to see in prod 🚀

feat: add different food sizes, increase food count, add food respawn, and make bots grow proportionally

---

other/CodeRunner.spec.ts
other/CodeRunner.ts
server/plugins/engine.ts

If the speed improvement is enough, this PR will eliminate a weird bot lag movement we are seeing on prod from time to time.
N/A

fix(engine): speed up the code runner (for up to 4.44 times)

---

other/CodeRunner.spec.ts

No immediate impact.
`CodeRunner` will be less likely to regress.
N/A

test(CodeRunner): ensure user's code can't call `fetch` and modify prototypes

---

other/CodeRunner.spec.ts
server/plugins/engine.ts

This PR will speed up code execution in the engine by parallelizing it.
Below are the results on some synthetic test with 10 sequential vs 10 parallel runs.
N/A

feat(engine): parallelize code execution

---

components/GameScreen.vue
tailwind.config.js

- Issue #48
- Allows users to zoom in in the game screen using mouse wheel on the mouse location.
- Allows user to pan through the game screen with mouse dragging.
- Max zoom in is 3 times.
- Currently panning outside the predefined spawn locations of the food doesn't look good.
- Same issue with zooming out

feat: zoom in on the game screen to show the players bot more closely and panning on game screen with mouse drag

---

other/world.spec.ts
other/world.ts

The game will lag less.
It is def not the most optimized version of this algorithm. We can return to it when we see issues with it.

perf: speedup world.getAvailableSpawnPositions and world.spawnFood with it

---

components/GameScreen.vue

perf(ui): always destroy graphics and its children when removing them

---

other/world.ts

https://github.com/user-attachments/assets/81bbe3a7-d674-49f4-b877-1c3518309d5e
https://github.com/user-attachments/assets/2619b75c-ebc0-4a05-88bf-50a87c83fa05
This PR introduces a method to dynamically calculate a bot's maximum movement distance (`maxBotMoveDistance`) based on its radius. Instead of relying on a fixed movement distance, the calculation now considers the bot's size using the new `getMaxBotMoveDistance` method.
Key changes:
1. **New parameters**:
- `moveDistanceChangePow`: Introduced to define the scaling power for movement distance (set to 0.45).
- Increased `maxMoveDistance` from 2 to 9 for greater flexibility.
2. **New method**:
- `getMaxBotMoveDistance(radius: number)`: Calculates the maximum movement distance for a bot using its radius, ensuring proportional scaling. …

feat: increase speed for small, and decrease speed for big bots

---

other/world.spec.ts
other/world.ts

The game engine will be faster, allowing us to run more games or bots simultaneously.
We could probably speed it up even more 😄

perf: speedup world.getAvailableSpawnPositions 7x
