move-fast-and-break-things/aibyss

- .github/workflows/validate.yaml
- .husky/pre-commit
- .vscode/settings.json
- components/CodeEditor.vue
- components/GameScreen.vue
- components/GlobalHeader.vue
- components/Header.vue
- eslint.config.mjs
- migrations/20240210182114_init/migration.sql
- nuxt.config.ts
- package-lock.json
- package.json
- pages/index.vue
- pages/login.vue
- server/api/auth/login.post.ts
- server/api/state.get.ts
- server/middleware/auth.ts
- server/plugins/engine.ts
- tailwind.config.js
- tsconfig.json
- utils/botApis/level01.js
- utils/botstore.ts
- utils/db.ts
- utils/getRandomElement.ts
- utils/sessionStorage.ts
- utils/world.ts
The app will have fewer regressions thanks to stricter type checking and linter rules introduced with this PR.
N/A
> chore: add eslint

- server/api/auth/login.post.ts
- utils/sessionStorage.ts
> feat(auth): fix session ttl constants

- .env
- .gitignore
It will be easier for us to start the server locally.
Ditto.
N/A
> fix: add dev `.env`

- components/CodeEditor.vue
- components/GameScreen.vue
> feat: add shadow border to the code editor and to the game screen

- components/CodeEditor.vue
https://github.com/move-fast-and-break-things/aibyss/assets/4187729/9fdfa351-8e26-4ed4-ae61-36b73191fcc5
https://github.com/move-fast-and-break-things/aibyss/assets/4187729/5ec1d5cb-450a-4ebf-8b70-02efe784e2dc
Ditto.
N/A
> feat(ui): better submit button

- package-lock.json
No impact.
Prisma asked me to update Prisma client.
N/A
> chore: update prisma-client and other deps

- README.md
- bin/create-user.ts
- package-lock.json
- package.json
- tests/utils/seed-test-users.ts
- utils/createUser.ts
No impact.
This PR lets developers create new users with the `npm run create-user` script.
N/A
> feat: add `create-user` script

- package-lock.json
- package.json
> chore: bump prisma

- components/GameScreen.vue
- server/api/state.get.ts
- server/plugins/engine.ts
There's some changes that restarting the game after a period of time or bot oversizing
> feat: added game restarting

- components/GlobalHeader.vue
- server/api/auth/logout.post.ts
Пользователь:
- будет видеть своё имя пользователя в верхнем правом углу (как подтверждение того, что он залогинен корректно)
- сможет разлогиниться
https://www.loom.com/share/5c38448aba774429b0befd2cf730c3aa
Нет.
> feat: logout button

- components/ButtonLink.vue
- components/CodeEditor.vue
- components/GlobalHeader.vue
- utils/defaultCode.ts
https://www.loom.com/share/4a91eb3a212a4b60880eb5a2b8c9b295
Нет.
> feat(code editor): add type checking, improve JSDoc, and move JSDoc to the API reference button

- package-lock.json
- package.json
> chore: bump deps, prisma and micromatch

- components/GameScreen.vue
> fix(ui): increase render resolution

- utils/prepareBotCode.ts
- utils/world.ts
Added console logging showing world stats (kills, deaths, count of eaten food)
> Added a Stats field containing world statistics

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This PR adds Contributing Guide and Code of Conduct
> docs: add contributing guide and code of conduct

- package-lock.json
No impact.
Prisma told me to update & I decided to update all deps.
N/A
> chore: update deps (prisma included)

- .dockerignore
- .github/workflows/deploy.yaml
- Dockerfile
- docker-compose.yml
- package.json
Closes #39 with:
- Aibyss is now life on https://aibyss.mfbt.community/
- new version of Aibyss will auto-deploy on every push to main
N/A
> feat: deploy Aibyss

- components/AnchorLink.vue
- components/GameScreen.vue
- components/GlobalHeader.vue
- components/RatingTable.vue
- pages/rating.vue
- server/api/rating.get.ts
This is a very naive and untested v1 of the rating algorithm. It will most likely be changed in the future. Ideas are welcome! 🎉
> feat: rating page

- components/CodeEditor.vue
> feat: block the "Submit" button on errors

- package-lock.json
- package.json
No impact.
Prisma asked me to update it, I have followed 😄 
N/A
> chore: update prisma

- components/RatingTable.vue
before:
after: 
Added K/D column to rating table
> feat(rating): add k/d column to rating table

- package-lock.json
- package.json
- server/middleware/auth.ts
- server/other/engineMetrics.ts
- server/plugins/engine.ts
- server/routes/metrics.ts
No direct impact.
This will help us debug performance issues :)
- we most likely will want to get rid of per-user metric at some point; but, for now, it's fine 😄
> feat: start collecting engine metrics

- components/GameScreen.vue
- components/GlobalHeader.vue
- server/middleware/auth.ts
https://github.com/user-attachments/assets/41f5cb0d-b87a-4852-bbc3-a905fdebe2bb
Made the rating page accessible to unauthenticated users by moving the link from game screen to the global header, and adding `/rating` and `/api/rating` to the list of public paths.
> feat(rating): make rating page publicly accessible

- package-lock.json
- package.json
> chore: update prisma to v6

- other/CodeRunner.spec.ts
- package-lock.json
- package.json
> chore: update deps
